version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: reza_user
      POSTGRES_PASSWORD: MyStr0ngP@ss
      POSTGRES_DB: reza_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: reza.8139@gmail.com
      PGADMIN_DEFAULT_PASSWORD: MyStr0ngP@ss
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db-data:
