# ---------- Stage 1: Build ----------
FROM golang:1.23 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o main ./cmd/api

# ---------- Stage 2: Run ----------
FROM debian:bullseye-slim

WORKDIR /app
COPY --from=builder /app/main .

# Expose API port
EXPOSE 8080

# Run the Go binary
CMD ["./main"]
